<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            [1,'Al-Fatihah',7,'Makkiyah'],
            [2,'Al-Baqarah',286,'Madaniyah'],
            [3,'Ali Imran',200,'Madaniyah'],
            [4,'An-Nisa',176,'Madaniyah'],
            [5,'Al-Ma\'idah',120,'Madaniyah'],
            [6,'Al-An\'am',165,'Makkiyah'],
            [7,'Al-A\'raf',206,'Makkiyah'],
            [8,'Al-Anfal',75,'Madaniyah'],
            [9,'At-Taubah',129,'Madaniyah'],
            [10,'Yunus',109,'Makkiyah'],
            [11,'Hud',123,'Makkiyah'],
            [12,'Yusuf',111,'Makkiyah'],
            [13,'Ar-Ra\'d',43,'Madaniyah'],
            [14,'Ibrahim',52,'Makkiyah'],
            [15,'Al-Hijr',99,'Makkiyah'],
            [16,'An-Nahl',128,'Makkiyah'],
            [17,'Al-Isra',111,'Makkiyah'],
            [18,'Al-Kahf',110,'Makkiyah'],
            [19,'Maryam',98,'Makkiyah'],
            [20,'Ta Ha',135,'Makkiyah'],
            [21,'Al-Anbiya',112,'Makkiyah'],
            [22,'Al-Hajj',78,'Madaniyah'],
            [23,'Al-Mu\'minun',118,'Makkiyah'],
            [24,'An-Nur',64,'Madaniyah'],
            [25,'Al-Furqan',77,'Makkiyah'],
            [26,'Asy-Syu\'ara',227,'Makkiyah'],
            [27,'An-Naml',93,'Makkiyah'],
            [28,'Al-Qasas',88,'Makkiyah'],
            [29,'Al-\'Ankabut',69,'Makkiyah'],
            [30,'Ar-Rum',60,'Makkiyah'],
            [31,'Luqman',34,'Makkiyah'],
            [32,'As-Sajdah',30,'Makkiyah'],
            [33,'Al-Ahzab',73,'Madaniyah'],
            [34,'Saba\'',54,'Makkiyah'],
            [35,'Fatir',45,'Makkiyah'],
            [36,'Ya-Sin',83,'Makkiyah'],
            [37,'As-Saffat',182,'Makkiyah'],
            [38,'Sad',88,'Makkiyah'],
            [39,'Az-Zumar',75,'Makkiyah'],
            [40,'Ghafir',85,'Makkiyah'],
            [41,'Fussilat',54,'Makkiyah'],
            [42,'Asy-Syura',53,'Makkiyah'],
            [43,'Az-Zukhruf',89,'Makkiyah'],
            [44,'Ad-Dukhan',59,'Makkiyah'],
            [45,'Al-Jasiyah',37,'Makkiyah'],
            [46,'Al-Ahqaf',35,'Makkiyah'],
            [47,'Muhammad',38,'Madaniyah'],
            [48,'Al-Fath',29,'Madaniyah'],
            [49,'Al-Hujurat',18,'Madaniyah'],
            [50,'Qaf',45,'Makkiyah'],
            [51,'Adz-Dzariyat',60,'Makkiyah'],
            [52,'At-Tur',49,'Makkiyah'],
            [53,'An-Najm',62,'Makkiyah'],
            [54,'Al-Qamar',55,'Makkiyah'],
            [55,'Ar-Rahman',78,'Madaniyah'],
            [56,'Al-Waqi\'ah',96,'Makkiyah'],
            [57,'Al-Hadid',29,'Madaniyah'],
            [58,'Al-Mujadilah',22,'Madaniyah'],
            [59,'Al-Hasyr',24,'Madaniyah'],
            [60,'Al-Mumtahanah',13,'Madaniyah'],
            [61,'As-Saff',14,'Madaniyah'],
            [62,'Al-Jumu\'ah',11,'Madaniyah'],
            [63,'Al-Munafiqun',11,'Madaniyah'],
            [64,'At-Taghabun',18,'Madaniyah'],
            [65,'At-Talaq',12,'Madaniyah'],
            [66,'At-Tahrim',12,'Madaniyah'],
            [67,'Al-Mulk',30,'Makkiyah'],
            [68,'Al-Qalam',52,'Makkiyah'],
            [69,'Al-Haqqah',52,'Makkiyah'],
            [70,'Al-Ma\'arij',44,'Makkiyah'],
            [71,'Nuh',28,'Makkiyah'],
            [72,'Al-Jinn',28,'Makkiyah'],
            [73,'Al-Muzzammil',20,'Makkiyah'],
            [74,'Al-Muddatsir',56,'Makkiyah'],
            [75,'Al-Qiyamah',40,'Makkiyah'],
            [76,'Al-Insan',31,'Madaniyah'],
            [77,'Al-Mursalat',50,'Makkiyah'],
            [78,'An-Naba\'',40,'Makkiyah'],
            [79,'An-Nazi\'at',46,'Makkiyah'],
            [80,'\'Abasa',42,'Makkiyah'],
            [81,'At-Takwir',29,'Makkiyah'],
            [82,'Al-Infitar',19,'Makkiyah'],
            [83,'Al-Mutaffifin',36,'Makkiyah'],
            [84,'Al-Insyiqaq',25,'Makkiyah'],
            [85,'Al-Buruj',22,'Makkiyah'],
            [86,'At-Tariq',17,'Makkiyah'],
            [87,'Al-A\'la',19,'Makkiyah'],
            [88,'Al-Ghasyiyah',26,'Makkiyah'],
            [89,'Al-Fajr',30,'Makkiyah'],
            [90,'Al-Balad',20,'Makkiyah'],
            [91,'Asy-Syams',15,'Makkiyah'],
            [92,'Al-Lail',21,'Makkiyah'],
            [93,'Ad-Dhuha',11,'Makkiyah'],
            [94,'Asy-Syarh',8,'Makkiyah'],
            [95,'At-Tin',8,'Makkiyah'],
            [96,'Al-\'Alaq',19,'Makkiyah'],
            [97,'Al-Qadr',5,'Makkiyah'],
            [98,'Al-Bayyinah',8,'Madaniyah'],
            [99,'Az-Zalzalah',8,'Madaniyah'],
            [100,'Al-\'Adiyat',11,'Makkiyah'],
            [101,'Al-Qari\'ah',11,'Makkiyah'],
            [102,'At-Takatsur',8,'Makkiyah'],
            [103,'Al-\'Asr',3,'Makkiyah'],
            [104,'Al-Humazah',9,'Makkiyah'],
            [105,'Al-Fil',5,'Makkiyah'],
            [106,'Quraisy',4,'Makkiyah'],
            [107,'Al-Ma\'un',7,'Makkiyah'],
            [108,'Al-Kautsar',3,'Makkiyah'],
            [109,'Al-Kafirun',6,'Makkiyah'],
            [110,'An-Nasr',3,'Madaniyah'],
            [111,'Al-Lahab',5,'Makkiyah'],
            [112,'Al-Ikhlas',4,'Makkiyah'],
            [113,'Al-Falaq',5,'Makkiyah'],
            [114,'An-Nas',6,'Makkiyah'],
        ];

        $rows = array_map(function ($s) {
            return [
                'nomor'       => $s[0],
                'nama_id'     => $s[1],
                'jumlah_ayat' => $s[2],
                'kategori'    => $s[3],
                'created_at'  => now(),
                'updated_at'  => now(),
            ];
        }, $surahs);

        // Idempotent: jika 'nomor' sudah ada, update kolom yang berubah
        DB::table('surahs')->upsert(
            $rows,
            ['nomor'], // unique key
            ['nama_id', 'jumlah_ayat', 'kategori', 'updated_at']
        );
    }
}